### ISSUE TITLE
tailwindcss-stimulus-components@4.0.4 is missing in unpkg

### ISSUE THREAD

**Issue by firewalker06** [excid3/madmin#176]
https://github.com/excid3/madmin/blob/14599a85f0fb687d6ad9bf30ee38db9f8b1abe3c/app/views/madmin/application/_javascript.html.erb#L16

> Failed to load resource: the server responded with a status of 404 ()

Checked in unpkg that its missing too: https://unpkg.com/browse/tailwindcss-stimulus-components@4.0.4

**Comment by firewalker06** [comment]
Update: it was fixed by https://github.com/excid3/madmin/pull/174 but not included in madmin 1.2.8 yet.

**Comment by moladukes** [comment]
> Update: it was fixed by #174 but not included in madmin 1.2.8 yet.

Hot linking the git url in the gem doesn't solve the issue for me. How did you resolve?

**Comment by moladukes** [comment]
Actually It may be a different issue. The select component doesn't seem to work and looking at the excid3 tailwind components I dont see a select component?

**Comment by candland** [comment]
Seeing this with v5.1.1: https://unpkg.com/tailwindcss-stimulus-components@5.1.1/dist/tailwindcss-stimulus-components.modern.js - 404 error.

**Comment by kaka-ruto** [comment]
Could you check if this [PR](https://github.com/excid3/madmin/pull/230) fixes it?

Use

```rb
  gem "madmin", github: "kaka-ruto/madmin", branch: "belongs-to-collection"
```
And run `bundle update madmin`
